load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_fuzzing",
    sha256 = "71fa2724c9802c597199a86111a0499fc4fb22426d322334d3f191dadeff5132",
    strip_prefix = "rules_fuzzing-0.1.0",
    urls = ["https://github.com/bazelbuild/rules_fuzzing/archive/v0.1.0.zip"],
)

load("@rules_fuzzing//fuzzing:repositories.bzl", "rules_fuzzing_dependencies")

rules_fuzzing_dependencies()

load("@rules_fuzzing//fuzzing:init.bzl", "rules_fuzzing_init")

rules_fuzzing_init()

## Bazel does not support transitive WORKSPACE external dependencies - in order to avoid version conflicts
http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-2.2.2",
    urls = [
        "https://mirror.bazel.build/github.com/gflags/gflags/archive/v2.2.2.tar.gz",
        "https://github.com/gflags/gflags/archive/v2.2.2.tar.gz",
    ],
)

http_archive(
    name = "liblfds-lib",
    build_file = "@//liblfds.BUILD:BUILD",  # ?Bug? required final file to be "BUILD"
    strip_prefix = "liblfds-master",
    urls = ["https://github.com/liblfds/liblfds/archive/master.zip"],  # Contains all releases
)

http_archive(
    name = "glog",
    strip_prefix = "glog-master",
    urls = ["https://github.com/google/glog/archive/master.zip"],  # Contains all releases
)
